-- Generated INSERT statements for COUNTRIES
-- Source: sample_countries.csv
-- Total records: 5
-- Using sequence: COUNTRIES_SEQ

INSERT INTO COUNTRIES (ID, COUNTRY, ALPHA_2_CODE, ALPHA_3_CODE, NUMERIC) VALUES (COUNTRIES_SEQ.NEXTVAL, 'United States', 'US', 'USA', 840);
INSERT INTO COUNTRIES (ID, COUNTRY, ALPHA_2_CODE, ALPHA_3_CODE, NUMERIC) VALUES (COUNTRIES_SEQ.NEXTVAL, 'United Kingdom', 'GB', 'GBR', 826);
INSERT INTO COUNTRIES (ID, COUNTRY, ALPHA_2_CODE, ALPHA_3_CODE, NUMERIC) VALUES (COUNTRIES_SEQ.NEXTVAL, 'Germany', 'DE', 'DEU', 276);
INSERT INTO COUNTRIES (ID, COUNTRY, ALPHA_2_CODE, ALPHA_3_CODE, NUMERIC) VALUES (COUNTRIES_SEQ.NEXTVAL, 'France', 'FR', 'FRA', 250);
INSERT INTO COUNTRIES (ID, COUNTRY, ALPHA_2_CODE, ALPHA_3_CODE, NUMERIC) VALUES (COUNTRIES_SEQ.NEXTVAL, 'Japan', 'JP', 'JPN', 392);
